# Generated by Django 4.0.6 on 2022-08-02 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('dietary_fiber', models.IntegerField(default=0)),
                ('magnesium', models.IntegerField(default=0)),
                ('vitamin_c', models.IntegerField(default=0)),
                ('vitamin_d', models.IntegerField(default=0)),
                ('vitamin_b6', models.IntegerField(default=0)),
                ('vitamin_b12', models.IntegerField(default=0)),
                ('folic_acid', models.IntegerField(default=0)),
                ('tryptophan', models.IntegerField(default=0)),
                ('dha_epa', models.IntegerField(default=0)),
                ('is_beverage', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.category')),
            ],
        ),
    ]
