# Generated by Django 4.0.6 on 2022-08-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_created_at_food_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='foods.category'),
        ),
    ]
