# Generated by Django 4.0.6 on 2022-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_food_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='vitamin_c',
            new_name='vitamin_a',
        ),
        migrations.RemoveField(
            model_name='food',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_beverage',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='육류', max_length=30),
            preserve_default=False,
        ),
    ]
