# Generated by Django 4.0.6 on 2022-08-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_rename_vitamin_c_food_vitamin_a_remove_food_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
