# Generated by Django 4.0.6 on 2022-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_alter_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(blank=True, to='foods.category'),
        ),
    ]
