# Generated by Django 4.0.6 on 2022-08-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_remove_food_category_food_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
