# Generated by Django 4.0.6 on 2022-08-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='food',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
