# Generated by Django 4.0.6 on 2022-08-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_food_category'),
        ('nutrients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='category',
            field=models.ManyToManyField(blank=True, to='foods.category'),
        ),
    ]
