# Generated by Django 4.0.6 on 2022-08-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrients', '0003_rename_vitamin_c_nutrient_vitamin_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='category',
        ),
    ]
