# Generated by Django 4.0.6 on 2022-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_remove_food_category_food_category'),
        ('nutrients', '0005_nutrient_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='category',
        ),
        migrations.AddField(
            model_name='nutrient',
            name='category',
            field=models.ManyToManyField(blank=True, to='foods.category'),
        ),
    ]
