# Generated by Django 4.0.6 on 2022-08-02 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0004_food_created_at_food_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('remark', models.TextField()),
                ('pic1', models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d')),
                ('pic2', models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d')),
                ('pic3', models.ImageField(blank=True, upload_to='post/images/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('breakfast', models.ManyToManyField(blank=True, related_name='breakfast_food', to='foods.food')),
                ('dinner', models.ManyToManyField(blank=True, related_name='dinner_food', to='foods.food')),
                ('lunch', models.ManyToManyField(blank=True, related_name='lunch_food', to='foods.food')),
                ('snack', models.ManyToManyField(blank=True, related_name='snack_food', to='foods.food')),
            ],
        ),
    ]
